version: '3.7'
services:
  db:
    image: mongo
    ports:
      - '27017:27017'
  app:
    restart: always
    build: .
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - '80:3000'
    depends_on:
      - db
